version: "3.8"

services:
  # Local Home Assistant stable environment for dynamic custom component integration testing
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
      - /var/run/dbus:/var/run/dbus:ro
    environment:
      - TZ=Australia/Sydney
    restart: unless-stopped
    network_mode: host


